builders:
  annotation_build:
    import: "package:ezflap/src/Annotations/Builder.dart"
    builder_factories: ["annotationBuilder"]
    build_extensions: {".dart": ["annotation.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]